[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "cdc_1C"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.33.0",
    "sqlalchemy>=2.0.49",
    "xmltodict>=1.0.4",
]

[tool.hatch.build.targets.wheel]
packages = ["src/cdc_1C"]